name: rst-converter-service CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag rst-converter-service
    - name: run pytest in Docker
      run: docker run --entrypoint=pytest rst-converter-service test_api.py
